# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import get_operation_pb2 as get__operation__pb2


class GetOperationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.addToClientDB = channel.unary_unary(
        '/GetOperation/addToClientDB',
        request_serializer=get__operation__pb2.RequestOperation.SerializeToString,
        response_deserializer=get__operation__pb2.ResponseOfOperation.FromString,
        )


class GetOperationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def addToClientDB(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetOperationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'addToClientDB': grpc.unary_unary_rpc_method_handler(
          servicer.addToClientDB,
          request_deserializer=get__operation__pb2.RequestOperation.FromString,
          response_serializer=get__operation__pb2.ResponseOfOperation.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GetOperation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
